taxi_admin_propietario:
    resource: "@TaxiAdminPropietarioBundle/Controller/"
    type:     annotation
    prefix:   /

taxi_admin_empresa:
    resource: "@TaxiAdminEmpresaBundle/Controller/"
    type:     annotation
    prefix:   /

taxi_admin_sitio:
    resource: "@TaxiAdminSitioBundle/Controller"
    type:     annotation

# import routes from a controller directory
taxi_admin_usuario:
    resource: "@TaxiAdminUsuarioBundle/Controller"
    type:     annotation

# login_check:
#     pattern:  /usuario/login_check

# login:
#     pattern:   /login
#     defaults:  { _controller: TaxiAdminSitioBundle:Sitio:login }
