propel:

  evento:
    id:         ~
    idUsuario:  { type: integer, required: true }
    evento:     { type: varchar(300), required: true }
    fecha:      { type: timestamp, required: true }    
    
  usuario:
    id:         ~
    tipo:       { type: varchar(20), required: true }
    nombre:     { type: varchar(20), required: true }
    apellidos:  { type: varchar(30), required: true }
    celular:    { type: varchar(15), required: false }
    telefono:   { type: varchar(15), required: false }
    direccion:  { type: varchar(100), required: true }
    email:      { type: varchar(100), required: true }
    clave:      { type: varchar(32), required: true }
    fechaAlta:  { type: timestamp, required: true }
    fechaBaja:  { type: timestamp, required: false }
    habilitado: { type: boolean, required: true, default: 1 }
    
  propietario:
    id:         ~
    cedula:     { type: integer, required: true}
    nombre:     { type: varchar(50), required: true }
    apellidos:  { type: varchar(50), required: true }
    direccion:  { type: varchar(100), required: false }
    telefono:   { type: varchar(15), required: false }
    celular:    { type: varchar(15), required: false }
    email:      { type: varchar(100), required: false }
    fechaAlta:  { type: timestamp, required: true }
    fechaBaja:  { type: timestamp, required: false }
    habilitado: { type: boolean, required: false, default: 1 }
    usuario:    { type: integer, foreignTable: usuario, foreignReference: id, required: true, onDelete: CASCADE }
      
  banco:
    id:         ~
    nombre:     { type: varchar(100), required: false }
    sucursal:   { type: varchar(100), required: false }
    direccion:  { type: varchar(100), required: false }
    web:        { type: varchar(100), required: false }
    fechaAlta:  { type: timestamp, required: true }
    fechaBaja:  { type: timestamp, required: false }
    habilitado: { type: boolean, required: false, default: 1 }
    usuario:    { type: integer, foreignTable: usuario, foreignReference: id, required: true, onDelete: CASCADE }
    
  empresa:
    id:           ~
    nombre:       { type: varchar(100), required: true }
    razonSocial:  { type: varchar(50), required: true }
    idBanco:      { type: integer, foreignTable: banco, foreignReference: id, required: false }
    numeroCuenta: { type: varchar(20), required: false }
    fechaAlta:    { type: timestamp, required: true }
    fechaBaja:    { type: timestamp, required: false }
    habilitado:   { type: boolean, required: false, default: 1 }
    usuario:      { type: integer, foreignTable: usuario, foreignReference: id, required: true, onDelete: CASCADE }
        
  taller:
    id:         ~
    nombre:     { type: varchar(100), required: true }
    direccion:  { type: varchar(100), required: true }
    telefono:   { type: varchar(15), required: true }
    telefono2:  { type: varchar(15), required: false }
    web:        { type: varchar(100), required: false}
    email:      { type: varchar(100), required: false}
    fechaAlta:  { type: timestamp, required: true }
    fechaBaja:  { type: timestamp, required: false }
    habilitado: { type: boolean, required: false, default: 1 }
    usuario:    { type: integer, foreignTable: usuario, foreignReference: id, required: true, onDelete: CASCADE }
    
  aseguradora:
    id:         ~
    nombre:     { type: varchar(100), required: true }
    direccion:  { type: varchar(100), required: true }
    telefono:   { type: varchar(15), required: true }
    telefono2:  { type: varchar(15), required: false }
    telefono3:  { type: varchar(15), required: false }
    web:        { type: varchar(100), required: false}
    email:      { type: varchar(100), required: false}
    fechaAlta:  { type: timestamp, required: true }
    fechaBaja:  { type: timestamp, required: false }
    habilitado: { type: boolean, required: false, default: 1 }
    usuario:    { type: integer, foreignTable: usuario, foreignReference: id, required: true, onDelete: CASCADE }
    
  despacho:
    id:          ~
    nombre:      { type: varchar(100), required: false }
    descripcion: { type: varchar(200), required: false }
    fechaAlta:   { type: timestamp, required: true }
    fechaBaja:   { type: timestamp, required: false }
    habilitado:  { type: boolean, required: false, default: 1 }
    usuario:     { type: integer, foreignTable: usuario, foreignReference: id, required: true, onDelete: CASCADE }
  
  chofer:
    id:                         ~
    cedula:                     { type: integer, required: true }
    nombre:                     { type: varchar(50), required: true }
    apellidos:                  { type: varchar(50), required: true }
    direccion:                  { type: varchar(100), required: false }
    telefono:                   { type: varchar(15), required: false }
    celular:                    { type: varchar(15), required: false }
    email:                      { type: varchar(100), required: false }
    aporteLeyes:                { type: decimal, size: 10, scale: 4, required: true }
    porcentajeLiquidacion:      { type: decimal, size: 10, scale: 4, required: true }
    vencimientoLibretaConducir: { type: date, required: false }
    vencimientoCarneSalud:      { type: date, required: false }
    fechaAlta:                  { type: timestamp, required: true }
    fechaBaja:                  { type: timestamp, required: false }
    habilitado:                 { type: boolean, required: false, default: 1 }
    usuario:                    { type: integer, foreignTable: usuario, foreignReference: id, required: true, onDelete: CASCADE }
        
  movil:
    id:            ~
    matricula:     { type: varchar(15), required: true } 
    marca:         { type: varchar(20), required: true }
    modelo:        { type: varchar(20), required: true }
    anio:          { type: integer, required: true }
    numeroChasis:  { type: varchar(50), required: false }
    combustible:   { type: varchar(50), required: true }
    numeroMovil:   { type: integer, required: false }
    idDespacho:    { type: integer, foreignTable: despacho, foreignReference: id, required: true }
    kmIniciales:   { type: integer, required: true }
    idAseguradora: { type: integer, foreignTable: aseguradora, foreignReference: id, required: false }
    fechaAlta:     { type: timestamp, required: true }
    fechaBaja:     { type: timestamp, required: false }
    habilitado:    { type: boolean, required: false, default: 1 }
    usuario:       { type: integer, foreignTable: usuario, foreignReference: id, required: true, onDelete: CASCADE }

  multa:
    id:                ~
    idChofer:          { type: integer, foreignTable: chofer, foreignReference: id, required: true, onDelete: CASCADE }
    idMovil:           { type: integer, foreignTable: movil, foreignReference: id, required: true, onDelete: CASCADE }
    fecha:             { type: date, required: false }
    descripcion:       { type: varchar(200), required: false }
    esquina:           { type: varchar(200), required: false }
    responsable:       { type: varchar(100), required: false }
    costo:             { type: decimal, size: 17, scale: 2, required: false }
    fechaVencimiento:  { type: date, required: false }
    pago:              { type: boolean, required: true, default: 0 }
    fechaPago:         { type: date, required: false }
    fechaAlta:         { type: timestamp, required: false }
    fechaBaja:         { type: timestamp, required: false }
    habilitado:        { type: boolean, required: false, default: 1 }
    usuario:           { type: integer, foreignTable: usuario, foreignReference: id, required: true, onDelete: CASCADE }
      
  accidente:
    id:          ~
    idChofer:    { type: integer, foreignTable: chofer, foreignReference: id, required: true, onDelete: CASCADE }
    idMovil:     { type: integer, foreignTable: movil, foreignReference: id, required: true, onDelete: CASCADE }
    fecha:       { type: date, required: true }
    responsable: { type: varchar(100), required: false }
    esquina:     { type: varchar(200), required: true }
    heridos:     { type: integer, required: false, default: 0 }
    deducible:   { type: boolean, required: false, default: false }
    descripcion: { type: varchar(200), required: false }
    fechaAlta:   { type: timestamp, required: true }
    fechaBaja:   { type: timestamp, required: false }
    habilitado:  { type: boolean, required: false, default: 1 }
    usuario:     { type: integer, foreignTable: usuario, foreignReference: id, required: true, onDelete: CASCADE }

  recaudacion:
    id:            ~
    idMovil:       { type: integer, foreignTable: movil, foreignReference: id, required: true, onDelete: CASCADE }
    idChofer:      { type: integer, foreignTable: chofer, foreignReference: id, required: true, onDelete: CASCADE }
    fecha:         { type: date, required: true }
    km:            { type: decimal, size: 17, scale: 2, required: true }
    recaudacion:   { type: decimal, size: 17, scale: 2, required: true }
    totalGastos:   { type: decimal, size: 17, scale: 2, required: true }
    importeChofer: { type: decimal, size: 17, scale: 2, required: true }
    importeMovil:  { type: decimal, size: 17, scale: 2, required: true }
    aporteLeyes:   { type: decimal, size: 17, scale: 2, required: true }
    fechaAlta:     { type: timestamp, required: true }
    fechaBaja:     { type: timestamp, required: false }
    habilitado:    { type: boolean, required: false, default: 1 }
    usuario:       { type: integer, foreignTable: usuario, foreignReference: id, required: true, onDelete: CASCADE }

  gastoRecaudacion:
    id:            ~
    idRecaudacion: { type: integer, foreignTable: recaudacion, foreignReference: id, required: false, onDelete: CASCADE }
    costo:         { type: decimal, size: 17, scale: 2, required: true }
    detalle:       { type: varchar(300), required: false }
    usuario:       { type: integer, foreignTable: usuario, foreignReference: id, required: true, onDelete: CASCADE }

  gastoMovil:
    id:            ~
    idMovil:       { type: integer, foreignTable: movil, foreignReference: id, required: true, onDelete: CASCADE }
    fecha:         { type: date, required: true }
    costo:         { type: decimal, size: 17, scale: 2, required: true }
    detalle:       { type: varchar(300), required: true }
    fechaAlta:     { type: timestamp, required: true }
    fechaBaja:     { type: timestamp, required: false }
    habilitado:    { type: boolean, required: false, default: 1 }
    usuario:       { type: integer, foreignTable: usuario, foreignReference: id, required: true, onDelete: CASCADE }

  gastoEmpresa:
    id:            ~
    idEmpresa:     { type: integer, foreignTable: empresa, foreignReference: id, required: true, onDelete: CASCADE }
    fecha:         { type: date, required: true }
    costo:         { type: decimal, size: 17, scale: 2, required: true }
    detalle:       { type: varchar(300), required: true }
    fechaAlta:     { type: timestamp, required: true }
    fechaBaja:     { type: timestamp, required: false }
    habilitado:    { type: boolean, required: false, default: 1 }
    usuario:       { type: integer, foreignTable: usuario, foreignReference: id, required: true, onDelete: CASCADE }

  configuracion:
    idUsuario:        { type: integer, foreignTable: usuario, foreignReference: id, required: true, onDelete: CASCADE }
    fichaNocturna:    { type: decimal, size: 17, scale: 2, required: true }
    fichaDiurna:      { type: decimal, size: 17, scale: 2, required: true }
    banderaDiurna:    { type: decimal, size: 17, scale: 2, required: true }
    banderaNocturna:  { type: decimal, size: 17, scale: 2, required: true }
    avisoVencimiento: { type: boolean, required: true, default: 1 }
    
  pagoAseguradora:
    idEmpresa:           { type: integer, foreignTable: empresa, foreignReference: id, required: true, onDelete: CASCADE, primaryKey: true }
    idAseguradora:       { type: integer, foreignTable: aseguradora, foreignReference: id, required: true, onDelete: CASCADE, primaryKey: true }
    idMovil:             { type: integer, foreignTable: movil, foreignReference: id, required: true, onDelete: CASCADE, primaryKey: true }
    pagoCorrespondiente: { type: date, required: true, primaryKey: true }
    monto:               { type: decimal, size: 17, scale: 2, required: true }
    fechaPago:           { type: date, required: true }
    fechaAlta:           { type: timestamp, required: true }
    fechaBaja:           { type: timestamp, required: false }
    habilitado:          { type: boolean, required: false, default: 1 }
    usuario:             { type: integer, foreignTable: usuario, foreignReference: id, required: true, onDelete: CASCADE }
  
  trabajoTaller:
    id:              ~
    idMovil:         { type: integer, foreignTable: movil, foreignReference: id, required: true, onDelete: CASCADE }
    idTaller:        { type: integer, foreignTable: taller, foreignReference: id, required: true, onDelete: CASCADE }
    fechaIngreso:    { type: date, required: false }
    motivoIngreso:   { type: varchar(200), required: false }
    costoMateriales: { type: decimal, size: 17, scale: 2, required: false }
    costoManoObra:   { type: decimal, size: 17, scale: 2, required: false }
    detalleTrabajo:  { type: varchar(200), required: false }
    responsable:     { type: varchar(150), required: false }
    tipoPago: ﻿  ﻿     { type: varchar(150), required: false }
    totalTrabajo:    { type: decimal, size: 17, scale: 2, required: false }
    numeroFactura:   { type: varchar(50), required: false }
    fechaAlta:       { type: timestamp, required: true }
    fechaBaja:       { type: timestamp, required: false }
    habilitado:      { type: boolean, required: false, default: 1 }
    usuario:         { type: integer, foreignTable: usuario, foreignReference: id, required: true, onDelete: CASCADE }

  adelanto:
    id:         ~
    idChofer:   { type: integer, foreignTable: chofer, foreignReference: id, required: true, onDelete: CASCADE }
    fecha:      { type: date, required: true }
    monto:      { type: decimal, size: 17, scale: 2, required: true }
    saldo:      { type: decimal, size: 17, scale: 2, required: false }
    detalle:    { type: varchar(150), required: false }
    fechaAlta:  { type: timestamp, required: true }
    fechaBaja:  { type: timestamp, required: false }
    habilitado: { type: boolean, required: false, default: 1 }
    usuario:    { type: integer, foreignTable: usuario, foreignReference: id, required: true, onDelete: CASCADE }
    
  pagoAdelanto:
    id:         ~
    idAdelanto: { type: integer, foreignTable: adelanto, foreignReference: id, required: true, onDelete: CASCADE }
    fecha:      { type: date, required: true }
    monto:      { type: decimal, size: 17, scale: 2, required: true }
    detalle:    { type: varchar(150), required: false }
    fechaAlta:  { type: timestamp, required: true }
    fechaBaja:  { type: timestamp, required: false }
    habilitado: { type: boolean, required: false, default: 1 }
    usuario:    { type: integer, foreignTable: usuario, foreignReference: id, required: true, onDelete: CASCADE }    
    
  empresa_propietario:
    idEmpresa:     { type: integer, foreignTable: empresa, foreignReference: id, required: true, onDelete: CASCADE, primaryKey: true }
    idPropietario: { type: integer, foreignTable: propietario, foreignReference: id, required: true, onDelete: CASCADE, primaryKey: true }
    fechaAlta:     { type: timestamp, required: true }
    fechaBaja:     { type: timestamp, required: false }
    habilitado:    { type: boolean, required: false, default: 1 }
    usuario:       { type: integer, foreignTable: usuario, foreignReference: id, required: true, onDelete: CASCADE }    
    
  movil_aseguradora:
    idMovil:       { type: integer, foreignTable: movil, foreignReference: id, required: true, onDelete: CASCADE, primaryKey: true }
    idAseguradora: { type: integer, foreignTable: aseguradora, foreignReference: id, required: true, onDelete: CASCADE }
    fechaAlta:     { type: timestamp, required: true }
    fechaBaja:     { type: timestamp, required: false }
    habilitado:    { type: boolean, required: false, default: 1 }
    usuario:       { type: integer, foreignTable: usuario, foreignReference: id, required: true, onDelete: CASCADE }    
    
  movil_despacho:
    idMovil:    { type: integer, foreignTable: movil, foreignReference: id, required: true, onDelete: CASCADE, primaryKey: true }
    idDespacho:    { type: integer, foreignTable: despacho, foreignReference: id, required: true, onDelete: CASCADE, primaryKey: true }
    fechaAlta:  { type: timestamp, required: true }
    fechaBaja:  { type: timestamp, required: false }
    habilitado: { type: boolean, required: false, default: 1 }
    
  movil_empresa:
    idMovil:    { type: integer, foreignTable: movil, foreignReference: id, required: true, onDelete: CASCADE, primaryKey: true }
    idEmpresa:  { type: integer, foreignTable: empresa, foreignReference: id, required: true, onDelete: CASCADE, primaryKey: true  }
    fechaAlta:  { type: timestamp, required: true }
    fechaBaja:  { type: timestamp, required: false }
    habilitado: { type: boolean, required: false, default: 1 }
    usuario:    { type: integer, foreignTable: usuario, foreignReference: id, required: true, onDelete: CASCADE }    
            
  chofer_empresa:
    idChofer:   { type: integer, foreignTable: chofer, foreignReference: id, required: true, onDelete: CASCADE, primaryKey: true }
    idEmpresa:  { type: integer, foreignTable: empresa, foreignReference: id, required: true, onDelete: CASCADE, primaryKey: true }
    fechaAlta:  { type: timestamp, required: true }
    fechaBaja:  { type: timestamp, required: false }
    habilitado: { type: boolean, required: false, default: 1 }
    usuario:    { type: integer, foreignTable: usuario, foreignReference: id, required: true, onDelete: CASCADE }    
